import {
  mkdirSync,
  copyFileSync,
  readFileSync,
  writeFileSync,
  existsSync,
} from "node:fs";
import { join } from "node:path";
import { releaseInfo, compareVersions } from "./release-lib.mjs";

export const repositoryUrl = "https://github.com/schachfeld/easy-mode-lighting";
export const imageName = "ghcr.io/schachfeld/easy-mode-lighting";

export function writeCatalog(source, destination, { revision, digest }) {
  if (!/^[a-f0-9]{40}$/.test(revision ?? ""))
    throw new Error("A full release commit SHA is required.");
  if (!/^sha256:[a-f0-9]{64}$/.test(digest ?? ""))
    throw new Error("A published image digest is required.");
  const { version, config } = releaseInfo(source);
  const previousPath = join(destination, "release.json");
  if (existsSync(previousPath)) {
    const previous = JSON.parse(readFileSync(previousPath, "utf8"));
    const order = compareVersions(version, previous.version);
    if (order < 0)
      throw new Error(
        `Refusing to downgrade the catalog from ${previous.version} to ${version}.`,
      );
    if (
      order === 0 &&
      (previous.revision !== revision || previous.digest !== digest)
    )
      throw new Error(
        "An existing release cannot be replaced with a different commit or image.",
      );
  }
  mkdirSync(join(destination, "glow"), { recursive: true });
  writeFileSync(
    join(destination, "repository.yaml"),
    `name: Glow lighting\nurl: ${repositoryUrl}\nmaintainer: schachfeld\n`,
  );
  writeFileSync(
    join(destination, "glow/config.json"),
    JSON.stringify(
      { ...config, image: imageName, url: repositoryUrl },
      null,
      2,
    ) + "\n",
  );
  for (const name of ["DOCS.md", "CHANGELOG.md", "icon.png"])
    copyFileSync(join(source, name), join(destination, "glow", name));
  writeFileSync(
    join(destination, "glow/README.md"),
    "# Glow\n\nYour home, in a good light. Automatic rooms, simple light controls, and persistent scenes for Home Assistant.\n\nInstall, start, and enable **Show in sidebar**. Your existing rooms and lights appear automatically. No token or dashboard setup is required.\n",
  );
  writeFileSync(
    join(destination, "README.md"),
    `# Glow for Home Assistant\n\nAdd this app repository to Home Assistant:\n\n\`${repositoryUrl}#home-assistant\`\n\nThen install **Glow**, start it, and enable **Show in sidebar**. New published versions appear as normal app updates.\n\n[Source and release notes](${repositoryUrl})\n\nThis branch is generated by the release workflow. Do not edit it by hand.\n`,
  );
  writeFileSync(
    previousPath,
    JSON.stringify({ version, revision, digest }, null, 2) + "\n",
  );
  return version;
}
